data = [
    {
        "name": "Instagram",
        "follower_count": 685,
        "description": "Social media platform",
        "country": "United States",
    },
    {
        "name": "Cristiano Ronaldo",
        "follower_count": 679,
        "description": "Footballer",
        "country": "Portugal",
    },
    {
        "name": "Ariana Grande",
        "follower_count": 363,
        "description": "Musician and actress",
        "country": "United States",
    },
    {
        "name": "Dwayne Johnson",
        "follower_count": 382,
        "description": "Actor and professional wrestler",
        "country": "United States",
    },
    {
        "name": "Kylie Jenner",
        "follower_count": 381,
        "description": "Reality TV personality and businesswoman",
        "country": "United States",
    },
    {
        "name": "Selena Gomez",
        "follower_count": 404,
        "description": "Musician and actress",
        "country": "United States",
    },
    {
        "name": "Kim Kardashian",
        "follower_count": 344,
        "description": "Reality TV personality and businesswoman",
        "country": "United States",
    },
    {
        "name": "Lionel Messi",
        "follower_count": 516,
        "description": "Footballer",
        "country": "Argentina",
    },
    {
        "name": "Beyoncé",
        "follower_count": 299,
        "description": "Musician",
        "country": "United States",
    },
    {
        "name": "Neymar",
        "follower_count": 242,
        "description": "Footballer",
        "country": "Brasil",
    },
    {
        "name": "National Geographic",
        "follower_count": 268,
        "description": "Magazine",
        "country": "United States",
    },
    {
        "name": "Justin Bieber",
        "follower_count": 286,
        "description": "Musician",
        "country": "Canada",
    },
    {
        "name": "Taylor Swift",
        "follower_count": 273,
        "description": "Musician",
        "country": "United States",
    },
    {
        "name": "Kendall Jenner",
        "follower_count": 277,
        "description": "Model and Reality TV personality",
        "country": "United States",
    },
    {
        "name": "Jennifer Lopez",
        "follower_count": 240,
        "description": "Musician and Actress",
        "country": "United States",
    },
    {
        "name": "Nike",
        "follower_count": 291,
        "description": "Sportswear multinational",
        "country": "United States",
    },
    {
        "name": "Khloé Kardashian",
        "follower_count": 292,
        "description": "Reality TV personality and businesswoman",
        "country": "United States",
    },
    {
        "name": "Miley Cyrus",
        "follower_count": 205,
        "description": "Musician and Actress",
        "country": "United States",
    },
    {
        "name": "Katy Perry",
        "follower_count": 195,
        "description": "Musician",
        "country": "United States",
    },
    {
        "name": "Kourtney Kardashian",
        "follower_count": 209,
        "description": "Reality TV personality",
        "country": "United States",
    },
    {
        "name": "Kevin Hart",
        "follower_count": 172,
        "description": "Comedian and actor",
        "country": "United States",
    },
    {
        "name": "Real Madrid CF",
        "follower_count": 180,
        "description": "Football club",
        "country": "Spain",
    },
    {
        "name": "FC Barcelona",
        "follower_count": 147,
        "description": "Football club",
        "country": "Spain",
    },
    {
        "name": "Rihanna",
        "follower_count": 145,
        "description": "Musician and businesswoman",
        "country": "Barbados",
    },
    {
        "name": "Demi Lovato",
        "follower_count": 147,
        "description": "Musician and actress",
        "country": "United States",
    },
    {
        "name": "Victoria's Secret",
        "follower_count": 76,
        "description": "Lingerie brand",
        "country": "United States",
    },
    {
        "name": "Zendaya",
        "follower_count": 177,
        "description": "Actress and musician",
        "country": "United States",
    },
    {
        "name": "Shakira",
        "follower_count": 103,
        "description": "Musician",
        "country": "Colombia",
    },
    {
        "name": "Drake",
        "follower_count": 139,
        "description": "Musician",
        "country": "Canada",
    },
    {
        "name": "Chris Brown",
        "follower_count": 140,
        "description": "Musician",
        "country": "United States",
    },
    {
        "name": "Vin Diesel",
        "follower_count": 103,
        "description": "Actor",
        "country": "United States",
    },
    {
        "name": "Cardi B",
        "follower_count": 161,
        "description": "Musician",
        "country": "United States",
    },
    {
        "name": "David Beckham",
        "follower_count": 87,
        "description": "Footballer",
        "country": "United Kingdom",
    },
    {
        "name": "Billie Eilish",
        "follower_count": 124,
        "description": "Musician",
        "country": "United States",
    },
    {
        "name": "Justin Timberlake",
        "follower_count": 72,
        "description": "Musician and actor",
        "country": "United States",
    },
    {
        "name": "NBA",
        "follower_count": 88,
        "description": "Club Basketball Competition",
        "country": "United States",
    },
]